### ISSUE TITLE
Bug Reporting 🐞

### ISSUE THREAD

**Issue by JordanLeich** [JordanLeich/Ultimate-Calculator#7]
- If you find any bugs or issues while using this project, report the bug here and we will fix it as soon as possible.

**Comment by PeanutbutterWarrior** [comment]
The basic calculation doesn't let you use brackets or follow operator precedence. I'd suggest taking a input for the whole calculation and calling `eval` on it. Eval does raise a risk of arbitrary code execution, but since this is only a local project it does not matter, and if it does then a regex could be run against it to only allow sensible characters. You could otherwise write a custom parser, but this is quite involved and unnecessary when python offers `eval`.

**Comment by JordanLeich** [comment]
@bot-coder05 ok, i will work on this now and try to resolve it.

**Comment by JordanLeich** [comment]
@bot-coder05 I was able to find the exact error you were talking but unfortunately, I'm not sure how to fix it, I've tried changing around the imports in the restart file but nothing works. Ideally, an end-user would not be running the project from any other file than the main.py file so they would not be capable of seeing this error message.

**Comment by mbcalli** [comment]
`> python3 main.py`


Traceback (most recent call last):
  File "~/Ultimate-Calculator/conversions/conversions.py", line 2, in <module>
    import winsound
ModuleNotFoundError: No module named 'winsound'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Ultimate-Calculator/main.py", line 9, in <module>
    import conversions.conversions
  File "~/Ultimate-Calculator/conversions/conversions.py", line 5, in <module>
    import winsound
ModuleNotFoundError: No module named 'winsound'



Running on MacOs.

**Comment by JordanLeich** [comment]
@mbcalli Thanks for reaching out about this, I just fixed this error message for you.

**Comment by mbcalli** [comment]
> @mbcalli Thanks for reaching out about this, I just fixed this error message for you.

Yes, fixed. Thank you.

**Comment by ShawnDriscoll** [comment]
When running main.exe:
NameError: name 'exit' is not defined in "gui.py" line 81

**Comment by JordanLeich** [comment]
> When running main.exe:
> 
> NameError: name 'exit' is not defined in "gui.py" line 81
> 
> 
> 
> Happens after choosing option 3.

I will look into this error.

**Comment by JordanLeich** [comment]
@ShawnDriscoll I have fixed the exit bug but please avoid using the GUI application while running the main.exe version since the GUI seems to be incompatible with how the main.exe file is created.
